### PR TITLE
add Maples7/barn

### PR DESCRIPTION
**Pull request by Maples7**
Thx~ :smiley:

### CODE REVIEW

**Comment by bamos** [comment]
Thanks :) Can you also add this to the commented string above the list?

**Comment by Maples7** [comment]
I don't get it. Where do you mean?

**Comment by bamos** [comment]
https://github.com/bamos/cv/pull/18/files#diff-04c6e90faac2675aa89e2176d2eec7d8L101

**Comment by bamos** [comment]
https://github.com/bamos/cv/pull/18/files#diff-04c6e90faac2675aa89e2176d2eec7d8L80

**Comment by Maples7** [comment]
I see, https://github.com/bamos/cv/pull/19

**Pull request closed without merging**
